package three.two.bit.phonemanager.domain.model

import kotlin.time.Clock
import kotlin.time.Instant
import three.two.bit.phonemanager.util.InviteCodeUtils

/**
 * Story E11.9: Represents an invite to join a group.
 *
 * Invites are generated by group admins/owners and can be shared via
 * code, QR code, or deep link. They have expiration times and usage limits.
 *
 * @property id Unique identifier for the invite
 * @property groupId The group this invite is for
 * @property groupName The name of the group (for display purposes)
 * @property code The 8-character invite code (e.g., "ABC12XYZ")
 * @property createdBy User ID who created the invite
 * @property createdAt When the invite was created
 * @property expiresAt When the invite expires
 * @property maxUses Maximum number of uses (-1 for unlimited)
 * @property usesRemaining Number of uses remaining
 * @property status Current status of the invite
 */
data class GroupInvite(
    val id: String,
    val groupId: String,
    val groupName: String? = null,
    val code: String,
    val createdBy: String,
    val createdAt: Instant,
    val expiresAt: Instant,
    val maxUses: Int = 1,
    val usesRemaining: Int = 1,
    val status: InviteStatus = InviteStatus.ACTIVE,
) {
    /**
     * Check if the invite has expired based on current time.
     *
     * @return true if the current time is past the expiry time
     */
    fun isExpired(): Boolean = Clock.System.now() > expiresAt

    /**
     * Check if the invite is still valid for use.
     * An invite is valid if:
     * - Status is ACTIVE
     * - Not expired
     * - Has uses remaining (or unlimited uses)
     *
     * @return true if the invite can be used
     */
    fun isValid(): Boolean =
        status == InviteStatus.ACTIVE &&
            !isExpired() &&
            (usesRemaining > 0 || maxUses == -1)

    /**
     * Check if this is a multi-use invite (unlimited or > 1 uses).
     *
     * @return true if the invite can be used more than once
     */
    fun isMultiUse(): Boolean = maxUses == -1 || maxUses > 1

    /**
     * Get the deep link URL for this invite.
     *
     * @return Deep link URL in format phonemanager://join/{code}
     */
    fun getDeepLink(): String = InviteCodeUtils.generateDeepLink(code)

    /**
     * Get the shareable web URL for this invite.
     *
     * @return HTTPS URL in format https://phonemanager.app/join/{code}
     */
    fun getShareUrl(): String = "https://phonemanager.app/join/$code"

    /**
     * Get the time remaining until expiry.
     *
     * @return Duration in milliseconds until expiry, or 0 if already expired
     */
    fun getTimeRemainingMillis(): Long {
        val now = Clock.System.now()
        return if (expiresAt > now) {
            (expiresAt - now).inWholeMilliseconds
        } else {
            0L
        }
    }

    /**
     * Get the expiry urgency level based on time remaining.
     *
     * @return ExpiryUrgency level for UI color coding
     */
    fun getExpiryUrgency(): ExpiryUrgency {
        val remainingMs = getTimeRemainingMillis()
        return when {
            remainingMs <= 0 -> ExpiryUrgency.EXPIRED
            remainingMs < 60 * 60 * 1000 -> ExpiryUrgency.CRITICAL // < 1 hour
            remainingMs < 24 * 60 * 60 * 1000 -> ExpiryUrgency.WARNING // < 24 hours
            else -> ExpiryUrgency.NORMAL
        }
    }
}

/**
 * Story E11.9: Status of a group invite.
 *
 * Invites can be in various states depending on usage and admin actions.
 */
enum class InviteStatus {
    /**
     * Invite is active and can be used to join the group.
     */
    ACTIVE,

    /**
     * Invite has passed its expiration time.
     */
    EXPIRED,

    /**
     * Invite was manually revoked by an admin/owner.
     */
    REVOKED,

    /**
     * Invite has been fully used (all uses consumed).
     */
    USED;

    companion object {
        /**
         * Parse a status string from the API.
         *
         * @param value The status string (e.g., "active", "expired")
         * @return The corresponding InviteStatus, defaults to ACTIVE if unknown
         */
        fun fromString(value: String): InviteStatus = when (value.lowercase()) {
            "active" -> ACTIVE
            "expired" -> EXPIRED
            "revoked" -> REVOKED
            "used" -> USED
            else -> ACTIVE
        }
    }
}

/**
 * Story E11.9: Urgency level for invite expiry display.
 *
 * Used for UI color coding of expiry countdown.
 */
enum class ExpiryUrgency {
    /**
     * Normal state - plenty of time remaining (> 24h).
     */
    NORMAL,

    /**
     * Warning state - less than 24 hours remaining (yellow).
     */
    WARNING,

    /**
     * Critical state - less than 1 hour remaining (red).
     */
    CRITICAL,

    /**
     * Expired - invite is no longer valid.
     */
    EXPIRED,
}

/**
 * Story E11.9: Response from validating an invite code.
 *
 * Contains the validation result and group preview if valid.
 *
 * @property valid Whether the invite code is valid
 * @property group Group preview if valid (id, name, memberCount)
 * @property error Error message if invalid
 */
data class InviteValidationResult(
    val valid: Boolean,
    val group: GroupPreview? = null,
    val error: String? = null,
)

/**
 * Story E11.9: Preview of a group for invite validation.
 *
 * Shows limited group information before joining.
 *
 * @property id Group's unique identifier
 * @property name Group's display name
 * @property memberCount Number of members in the group
 */
data class GroupPreview(
    val id: String,
    val name: String,
    val memberCount: Int,
)

/**
 * Story E11.9: Result from joining a group with an invite code.
 *
 * @property groupId The group that was joined
 * @property role The role assigned to the new member
 * @property joinedAt When the user joined the group
 */
data class JoinGroupResult(
    val groupId: String,
    val role: GroupRole,
    val joinedAt: Instant,
)
